/**
 * `cerberus init [--agent claude|codex|cursor|cline] [--global] [--print]` — wire Cerberus's hook
 * into the target agent (M5). Safe by default: MERGE (never overwrite), IDEMPOTENT, BACK UP first.
 *
 * Each agent has a different hook config shape/location, so there's one installer per agent. The hook
 * command is always `node "<bin>" hook --agent <name>`; the per-agent adapter does the rest.
 *
 * VERIFICATION: `claude` is verified end-to-end. `codex`/`cursor`/`cline` configs follow the published
 * specs (late-2025/2026) and are flagged for live re-verification — use `--print` to preview/paste.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, chmodSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { rawEnv } from '../config/env.js';

const PACKAGE_ROOT = rawEnv('HOME') ?? process.cwd();
const BIN = join(PACKAGE_ROOT, 'bin', 'cerberus.mjs');
type Agent = 'claude' | 'codex' | 'cursor' | 'cline';
const AGENTS: readonly Agent[] = ['claude', 'codex', 'cursor', 'cline'];

// Quote the path so a Windows install dir with spaces still runs; tag the agent so the adapter is picked.
const cmd = (agent: Agent): string => `node "${BIN}" hook --agent ${agent}`;
const PRE_TIMEOUT = 310; // ≥ engine TTL for hold-mode agents (codex/cline); harmless for ask-mode.

interface HookCmd { type: 'command'; command: string; timeout?: number }
interface HookGroup { matcher?: string; hooks?: HookCmd[] }
type Json = Record<string, unknown>;

const wired = (command: string): boolean => command.includes(BIN) && /\bhook\b/.test(command);

function backupAndWrite(path: string, data: string): string {
  if (existsSync(path)) copyFileSync(path, `${path}.bak`);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, data);
  return existsSync(`${path}.bak`) ? `   Backup: ${path}.bak\n` : '';
}

const readJson = (path: string): Json => (existsSync(path) ? (JSON.parse(readFileSync(path, 'utf8')) as Json) : {});

/* ── Claude Code & Codex share the same hooks.json shape (Codex copied the spec) ── */
function claudeShapeConfig(agent: Agent): Json {
  const tool = (event: string): HookGroup => ({ matcher: '*', hooks: [{ type: 'command', command: cmd(agent), timeout: event === 'PreToolUse' ? PRE_TIMEOUT : 10 }] });
  const lifecycle = (): HookGroup => ({ hooks: [{ type: 'command', command: cmd(agent), timeout: 10 }] });
  return { hooks: { PreToolUse: [tool('PreToolUse')], PostToolUse: [tool('PostToolUse')], SessionStart: [lifecycle()], SessionEnd: [lifecycle()] } };
}

function mergeClaudeShape(path: string, agent: Agent): { added: number; unchanged: number } {
  const settings = readJson(path);
  const hooks = ((settings as { hooks?: Record<string, HookGroup[]> }).hooks ??= {});
  let added = 0, unchanged = 0;
  for (const [event, groups] of Object.entries((claudeShapeConfig(agent).hooks as Record<string, HookGroup[]>))) {
    const existing = (hooks[event] ??= []);
    if (!Array.isArray(existing)) continue;
    if (existing.some((g) => g.hooks?.some((h) => typeof h.command === 'string' && wired(h.command)))) unchanged++;
    else (existing.push(groups[0] as HookGroup), added++);
  }
  if (added > 0) backupAndWrite(path, JSON.stringify(settings, null, 2) + '\n');
  return { added, unchanged };
}

/* ── Cursor: { version, hooks: { beforeShellExecution: [{command, failClosed}], … } } ── */
function cursorConfig(): Json {
  const h = (): Json => ({ command: cmd('cursor'), failClosed: true }); // Cursor defaults fail-OPEN
  return { version: 1, hooks: { beforeShellExecution: [h()], beforeMCPExecution: [h()] } };
}

function mergeCursor(path: string): { added: number; unchanged: number } {
  const cfg = readJson(path);
  cfg['version'] ??= 1;
  const hooks = ((cfg as { hooks?: Record<string, Json[]> }).hooks ??= {});
  let added = 0, unchanged = 0;
  for (const [event, arr] of Object.entries(cursorConfig().hooks as Record<string, Json[]>)) {
    const existing = (hooks[event] ??= []);
    if (!Array.isArray(existing)) continue;
    if (existing.some((h) => typeof h['command'] === 'string' && wired(h['command'] as string))) unchanged++;
    else (existing.push(arr[0] as Json), added++);
  }
  if (added > 0) backupAndWrite(path, JSON.stringify(cfg, null, 2) + '\n');
  return { added, unchanged };
}

/* ── Cline: executable script files named exactly after the hook event (no JSON config) ── */
const CLINE_SCRIPT = (): string => `#!/bin/sh\n# Cerberus hook for Cline — auto-generated by \`cerberus init --agent cline\`.\nexec node "${BIN}" hook --agent cline\n`;
function installCline(dir: string): { added: number; unchanged: number } {
  let added = 0, unchanged = 0;
  for (const event of ['PreToolUse', 'PostToolUse']) {
    const file = join(dir, event);
    if (existsSync(file) && readFileSync(file, 'utf8').includes(BIN)) { unchanged++; continue; }
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, CLINE_SCRIPT());
    chmodSync(file, 0o755);
    added++;
  }
  return { added, unchanged };
}

/* ── paths per agent ── */
function configPath(agent: Agent, global: boolean): string {
  const home = homedir(), cwd = process.cwd();
  switch (agent) {
    case 'claude': return join(global ? home : cwd, '.claude', 'settings.json');
    case 'codex': return global ? join(home, '.codex', 'hooks.json') : join(cwd, '.codex', 'hooks.json');
    case 'cursor': return global ? join(home, '.cursor', 'hooks.json') : join(cwd, '.cursor', 'hooks.json');
    case 'cline': return global ? join(home, 'Documents', 'Cline', 'Rules', 'Hooks') : join(cwd, '.clinerules', 'hooks');
  }
}

export function runInit(argv: string[]): void {
  const global = argv.includes('--global');
  const printOnly = argv.includes('--print');
  const ai = argv.indexOf('--agent');
  const agent: Agent = ai >= 0 && AGENTS.includes(argv[ai + 1] as Agent) ? (argv[ai + 1] as Agent) : 'claude';
  const path = configPath(agent, global);

  if (printOnly) {
    if (agent === 'cline') {
      process.stdout.write(`Create executable files in ${path}/ named PreToolUse and PostToolUse, each:\n\n${CLINE_SCRIPT()}\nthen \`chmod +x\` them.\n`);
    } else {
      const snippet = agent === 'cursor' ? cursorConfig() : claudeShapeConfig(agent);
      process.stdout.write(`Merge into ${path}:\n\n${JSON.stringify(snippet, null, 2)}\n`);
    }
    return;
  }

  const r =
    agent === 'cursor' ? mergeCursor(path) : agent === 'cline' ? installCline(path) : mergeClaudeShape(path, agent);

  if (r.added === 0) {
    process.stdout.write(`Cerberus (${agent}) already wired at ${path} — nothing to do.\n`);
    return;
  }
  process.stdout.write(
    `✅ Wired Cerberus into ${agent} at ${path} (${r.added} added, ${r.unchanged} already present).\n` +
      (existsSync(`${path}.bak`) ? `   Backup: ${path}.bak\n` : '') +
      `\nNext:\n  1. cerberus engine          # start the gateway + dashboard\n  2. open http://127.0.0.1:9000/\n  3. use ${agent} as usual — tool calls now route through Cerberus.\n` +
      (agent === 'codex' || agent === 'cline' ? `  (HITL approvals: this agent has no native prompt → run with CB_APPROVAL_SURFACE=dashboard and approve in the UI / \`cerberus pending\`.)\n` : ''),
  );
}
